.TH pgrphack 8
.SH NAME
pgrphack \- runs a program in a separate process group.
.SH SYNOPSIS
.B pgrphack
.I child
.SH DESCRIPTION
.B pgrphack
runs
.I child
in a new process group.
.SH SEE ALSO
supervise(8),
svc(8),
svok(8),
svstat(8),
svscanboot(8),
svscan(8),
readproctitle(8),
fghack(8),  
multilog(8),
tai64n(8),
tai64nlocal(8),
setuidgid(8),
envuidgid(8),
envdir(8),
softlimit(8),
setlock(8)
