.TH svc 8
.SH NAME
svc \- controls services monitored by
.BR supervise(8).
.SH SYNOPSIS
.B svc
[
.B \-udopchaitkx
]
.I services
.SH DESCRIPTION
.I services
consists of any number of arguments, each argument naming a directory used by
.BR supervise (8).

.B svc
applies all the options to each
.I service
in turn.
.SH OPTIONS
.TP
.B \-u
Up. If the
.I service
is not running, start it. If the
.I service
stops, restart it. 
.TP
.B \-d
Down. If the
.I service
is running, send it a TERM signal and then a CONT signal. After it stops, do
not restart it. 
.TP
.B \-o
Once. If the
.I service
is not running, start it. Do not restart it if it stops. 
.TP
.B \-p
Pause. Send the
.I service
a STOP signal. 
.TP
.B \-c
Continue. Send the
.I service
a CONT signal. 
.TP
.B \-h
Hangup. Send the
.I service
a HUP signal. 
.TP
.B \-a
Alarm. Send the
.I service
an ALRM signal. 
.TP
.B \-i
Interrupt. Send the
.I service
an INT signal. 
.TP
.B \-t
Terminate. Send the
.I service
a TERM signal. 
.TP
.B \-k
Kill. Send the
.I service
a KILL signal. 
.TP
.B \-x
Exit.
.BR supervise (8)
will exit as soon as the
.I service
is down. If you use this option on a stable system, you're doing something
wrong;
.BR supervise (8)
is designed to run forever.
.SH SEE ALSO
supervise(8),
svok(8),
svstat(8),
svscanboot(8),
svscan(8),
readproctitle(8),
fghack(8),  
pgrphack(8),
multilog(8),
tai64n(8),
tai64nlocal(8),
setuidgid(8),
envuidgid(8),
envdir(8),
softlimit(8),
setlock(8)

http://cr.yp.to/daemontools.html
