.TH tai64n 8
.SH NAME
tai64n \- puts a precise timestamp on each line.
.SH SYNOPSIS
.B tai64n
.SH DESCRIPTION
.B tai64n
reads lines from stdin. For each line, it writes 
.IP 1
an @, 
.IP 2.
a precise timestamp, 
.IP 3.
a space, and 
.IP 4.
a copy of the input line 

to stdout. The timestamp indicates the moment that
.B tai64n
read the first character of the line. 

.B tai64n
does not allocate any memory after it starts.
.SH TIMESTAMPS
Timestamps used by
.B tai64n
are 12-byte TAI64N labels in external TAI64N format, printed as 24 lowercase
hexadecimal characters. You can use
.BR tai64nlocal (8)
to convert the timestamps to a human-readable format. 

For example, the timestamp 4000000037c219bf2ef02e94 refers to the nanosecond
beginning exactly 935467455.787492500 seconds after the beginning of 1970 TAI;
37c219bf hexadecimal is 935467455, and 2ef02e94 hexadecimal is 787492500. 

The current implementation of
.B tai64n
relies on the UNIX gettimeofday library routine to return the current time as
the number of TAI seconds since 1970-01-01 00:00:10 TAI. Beware that most
gettimeofday implementations are not Y2038-compliant. Furthermore, most clocks
are not set accurately. 
.SH EXIT CODES
.B tai64n
exits 0 when it sees end of input. It exits 111 without an error message if
it has trouble reading stdin or writing stdout. 
.SH SEE ALSO
envdir(8),
envini(8),
envuidgid(8),
fghack(8),  
multilog(8),
pgrphack(8),
readproctitle(8),
setlock(8),
setuidgid(8),
setuser(8),
softlimit(8),
supervise(8),
svc(8),
svok(8),
svscan(8),
svscanboot(8),
svstat(8),
tai64nlocal(8)
