--- fifo requires arguments
fifo: usage: fifo file child
100
--- fifo requires more arguments
fifo: usage: fifo file child
100
--- fifo complains if it cannot run program
fifo: warning: unable to exec ./nonexistent: file does not exist
fifo: warning: child died: status 111
fifo: fatal: child died before banner
111
--- fifo quits if child doesnt finish banner
fifostar
fifo: warning: child died: status 111
fifo: fatal: child died before banner
--- fifo runs a program
fifostart
hi there
--- fifo runs a program but child dies later
fifostart
Ticking away
fifo: warning: child died: status 121
 the moments that make
fifo: warning: child died: status 121
 up the dull day,
frit
fifo: warning: child died: status 121
ter and waste the hour
fifo: warning: child died: status 121
 in an offhand way.

