--- setlock requires arguments
setlock: usage: setlock [ -nNxX ] [ -p pidfile ] [ -t timeout ] [ -b blocktime ] file program [ arg ... ]
100
--- setlock complains if it cannot create lock file
setlock: fatal: unable to open nonexistent/lock: file does not exist
111
--- setlock -x exits quietly if it cannot create lock file
0
--- setlock creates lock file
ok
0
--- setlock does not truncate lock file
ok
0
--- setlock -n complains if file is already locked
setlock: fatal: unable to lock lock: temporary failure
111
--- setlock -nx exits quietly if file is already locked
two
0
--- setlock -t 2 -b 3 times out
setlock: info: lock request timeout after 2 seconds: timed out
--- setlock -t 999999 is rejected
setlock: bad parameter value: maximum timeout is 604800 seconds
setlock: usage: setlock [ -nNxX ] [ -p pidfile ] [ -t timeout ] [ -b blocktime ] file program [ arg ... ]
100
--- setlock -b 999999 is rejected
setlock: bad parameter value: maximum blocktime is 604800 seconds
setlock: usage: setlock [ -nNxX ] [ -p pidfile ] [ -t timeout ] [ -b blocktime ] file program [ arg ... ]
100
