--- supervise starts, svok works, svup works, svstat works, svc -x works
100
100
100
test.sv: down x seconds, stopped
0
0
test.sv: supervise not running
0
--- svc -ox works
hi
--- svstat and svup work for up services
.: up (pid x) x seconds, normally down, once, running
0
.: up (pid x) x seconds, normally down, once, running
0
.: no log service
0
0
100
0
--- svstat and svup work for logged services
.: up (pid x) x seconds, normally down, once, running
. log: up (pid x) x seconds, normally down, once, running
0
.: up (pid x) x seconds, normally down, once, running
0
. log: up (pid x) x seconds, normally down, once, running
0
0
0
0
--- svc -u works
first
second
